# Run Tests using pytest

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - 'jsolver/**'            # Only trigger on changes to source code files
      - '.github/workflows/**'  # Trigger on changes to workflow files
      - 'tests/**'              # Trigger on changes to tests
  pull_request:
    branches: [ "main" ]
    paths:
      - 'jsolver/**'            # Only trigger on changes to source code files
      - '.github/workflows/**'  # Trigger on changes to workflow files
      - 'tests/**'              # Trigger on changes to tests

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"  # Change to a specific version if needed
      
      # Runs a set of commands using the runners shell
      - name: Display Python and Pip version
        run: |
          python --version
          pip --version

      - name: Set up virtual environment
        run: |
          python -m venv jax
          source jax/bin/activate
          pip install .

      - name: Run tests with coverage
        run: |
          source jax/bin/activate
          pytest --cov=pysolver pysolver/tests --junitxml=pytest_results.xml --cov-report=xml --cov-report=html --cov-report=term
        env:
          COVERAGE_FILE: .coveragerc  # Ensures pytest-cov uses .coveragerc if not automatically detected

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pytest_results
          path: pytest_results.xml

      - name: Upload coverage report (XML)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-xml
          path: coverage.xml

      - name: Upload coverage HTML report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-html
          path: htmlcov/

    env:
      CACHE_DIR: .cache/pip  # Optional: add caching if needed
